# Generated by Django 2.2.16 on 2022-04-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220414_2144'),
        ('reviews', '0002_auto_20220414_1922'),
    ]

    operations = [
    ]
